"""Add shadow trading columns

Revision ID: 9033e2a4a2f9
Revises: 004_liquidation_aggregates
Create Date: 2026-03-27 09:55:52.404634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision = '9033e2a4a2f9'
down_revision = '004_liquidation_aggregates'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_market_data_symbol_time'), table_name='market_data')
    op.drop_index(op.f('market_data_timestamp_idx'), table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('idx_sentiment_time'), table_name='sentiment_embeddings')
    op.drop_table('sentiment_embeddings')
    op.alter_column('agent_status', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('agent_status', 'last_heartbeat',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('alerts', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('funding_rates_time_idx'), table_name='funding_rates')
    op.drop_index(op.f('liquidations_time_idx'), table_name='liquidations')
    op.alter_column('news_embeddings', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('news_embeddings', 'embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    op.drop_index(op.f('orderbook_snapshots_time_idx'), table_name='orderbook_snapshots')
    op.add_column('trade_audit_logs', sa.Column('latency_exec_ms', sa.Float(), nullable=True))
    op.add_column('trade_audit_logs', sa.Column('signal_price', sa.Float(), nullable=True))
    op.add_column('trade_audit_logs', sa.Column('simulated_fill_price', sa.Float(), nullable=True))
    op.add_column('trade_audit_logs', sa.Column('slippage_bps', sa.Float(), nullable=True))
    op.add_column('trade_audit_logs', sa.Column('simulated_fee_usdt', sa.Float(), nullable=True))
    op.add_column('trade_audit_logs', sa.Column('latency_ms', sa.Float(), nullable=True))
    op.add_column('trade_audit_logs', sa.Column('veto_reason', sa.String(length=255), nullable=True))
    op.alter_column('trade_audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade_audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('trade_audit_logs', 'veto_reason')
    op.drop_column('trade_audit_logs', 'latency_ms')
    op.drop_column('trade_audit_logs', 'simulated_fee_usdt')
    op.drop_column('trade_audit_logs', 'slippage_bps')
    op.drop_column('trade_audit_logs', 'simulated_fill_price')
    op.drop_column('trade_audit_logs', 'signal_price')
    op.drop_column('trade_audit_logs', 'latency_exec_ms')
    op.create_index(op.f('orderbook_snapshots_time_idx'), 'orderbook_snapshots', [sa.literal_column('time DESC')], unique=False)
    op.alter_column('news_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=True)
    op.alter_column('news_embeddings', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('liquidations_time_idx'), 'liquidations', [sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('funding_rates_time_idx'), 'funding_rates', [sa.literal_column('time DESC')], unique=False)
    op.alter_column('alerts', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('agent_status', 'last_heartbeat',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('agent_status', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_table('sentiment_embeddings',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sentiment_score', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sentiment_embeddings_pkey')),
    sa.UniqueConstraint('content_hash', name=op.f('sentiment_embeddings_content_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_sentiment_time'), 'sentiment_embeddings', ['timestamp'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True),
    sa.Column('high', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True),
    sa.Column('low', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True),
    sa.Column('close', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True),
    sa.Column('volume', sa.NUMERIC(precision=24, scale=8), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'timestamp', name=op.f('market_data_pkey'))
    )
    op.create_index(op.f('market_data_timestamp_idx'), 'market_data', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_market_data_symbol_time'), 'market_data', ['symbol', 'timestamp'], unique=False)
    # ### end Alembic commands ###
